config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create], path: 'posts' do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create, :destroy]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :posts, class_name: 'Post', foreign_key: 'post_id'
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'

  after_create :comment_count
  def comment_count
    posts.increment!(:comments_counter)
    posts.save
    posts.reload
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :posts, class_name: 'Post', foreign_key: 'post_id'
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  def like_count
    posts.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes, dependent: :destroy
  validates :user, presence: true
  validates :title, presence: true
  validates :text, presence: true
  validates :title, length: { maximum: 250, message: 'should be less than 250 characters' }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def posts_increment
    return unless user

    user.increment!(:posts_count)
    puts "Incremented user's posts_count to #{user.posts_count}"
  end

  def recent
    comments.order(created_at: :desc).limit(5)
  end

  after_create :increment_posts_count

  def increment_posts_count
    puts "Incrementing posts_count for user #{user.id}"
    user.increment!(:posts_count)
    user.save
    user.reload
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, dependent: :destroy
  validates :name, presence: true
  validates :posts_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :bio, :photo, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :new
  def new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = Comment.new(params.require(:comment).permit(:text).merge(author_id: current_user.id,
                                                                        post_id: params[:post_id]))
    @comment.save
    redirect_to user_post_path(@post.author_id, @post)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(author_id: current_user.id)
    end
    redirect_to user_post_path(@post.author_id, @post)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(author_id: current_user.id, post_id:
    params[:post_id]).exists?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @comments = Comment.includes(:user).all
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text).merge(author_id: current_user.id))
    if @post.save
      flash[:notice] = 'Post saved!'
      redirect_to user_posts_path(current_user.id)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/new.html.erb
<h1>Create a new comment</h1>

<%= form_with scope: :comment, data: {turbo: false}, url: user_post_comments_path, local: true do |f| %>

  <p>
    <%= f.label :text %></br>
    <%= f.text_area :text%>
  </p>
  <p> <%= f.submit %> </p>


<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if request.fullpath == "/users/sign_in" %>
      <style>
        .auth-btns {
           display: none;
          }
      </style>
    <% end %>
    <div class="auth-btns">
    <%= button_to "Sign in", new_user_session_path, method: :post, data: { turbo: false }  %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo: false }  %>
    <%= button_to "Sign up", new_user_registration_path, method: :get, data: { turbo: false }  %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>this is the home page</h1>
<h2>Here is a list of all users and number of posts</h2>

app/views/posts/index.html.erb
<h1>Posts index</h1>
<div class="users_container">
  <div class="square">
    <img src="<%= @user.photo %>">  
  </div>
  <div class= "user-info">  
    <h1><%= @user.name %></h1> 
    <p class="posts-number"><strong>Number of posts:</strong><%= @user.posts_count %></p>

  </div>
</div>
<% @user.posts.each do |post| %>
  <%= link_to user_post_path(:id => post.id ) do %>
  <div class="user-posts">
  <p><%=post.title %></p>
  <p><%=post.text %></p>
  <div class="counters">
    <p><strong><%= post.likes.count %> <%= (post.likes.count) <= 1 ? 'Like' : 'Likes'%></strong></p>  
    <p><strong>Comments:</strong> <%=post.comments_counter%></p>
  </div>
</div>
<%end%>
<% if post.comments_counter > 0 %>
<%= link_to user_post_path(:id => post.id ) do %>
<div class= "comments user-posts">
  <% @comments.each do |comment| %>
    <% if comment.post_id == post.id %>
        <div class= "comment">
          <%=comment.text %>
        </div>
    <%end%>
  <%end%>
</div>
<% end %>
<% end %>

<% end %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>
<% if @post.errors.any? %>
  <h2>The following errors prevented the post from saving: </h2>
  <ul>
  <% @post.errors.full_messages.each do |msg|%>
    <li><%= msg %></li>
  <%end%>
  </ul>
<%end%>

<%= form_with scope: :post, data: { turbo: false }, url: user_posts_path, local: true do |f| %>
<p>
  <%= f.label :title %></br>
  <%= f.text_field :title %>
</p>
<p> 
  <%= f.label :text %></br>
  <%= f.text_area :text%>
</p>
<p>
  <%= f.submit %>
</p>

<%end%>

app/views/posts/show.html.erb
<h1>Posts showing</h1>
<div class="main post-main">
  <div class="post-header">
    <span><strong>Post #<%= @post.id %> by <%= @user.name %> </strong></span>
  </div>
  <div class="post-body">

    <p><%= @post.title %></p>
    <p><%= @post.text %></p>
  </div>
</div>

<%= button_to 'Like', user_post_likes_path(@user, @post), method: :post, class: "btn btn-primary" %>

<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<div class="comments">

<% if @post.comments_counter > 0 %>
  <% @comments.each do |comment| %>
    <div class="commenter">
      <% author = User.find(comment.author_id) %>
      <p><%= author.name %>:</p>
      <p><%= comment.text %></p>
    </div>
  <% end %>
<% end %>
  <%= link_to "Add Comment", new_user_post_comment_path(@user, @post), class: "btn btn-primary" %>

</div>

app/views/users/index.html.erb
<div class="main">
  <h1>User index</h1>
  <% @users.each do |user| %>
    <%= link_to user_path(id: user.id), class:'user-link' do %>
      <div class="users_container user_wrap" >
          <div class="square"><img src="<%= user.photo %>"></div>
          <div class= "user-info">  
            <h1><%= user.name %></h1> 
            <p class="posts-number"><strong>Number of posts: </strong><%= user.posts_count %></p>  
          </div>
        </div>
    <% end %>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="main">
<h1>Showing user</h1>
  <div class="users_container">
    <div class="square">
      <img src="<%= @user.photo %>">
    </div>
    <div class= "user-info">  
      <h1><%= @user.name %></h1> 
      <p class="posts-number"><strong>Number of posts:</strong><%= @user.posts_count %></p>  
    </div>
  </div>
  <div class= "user-bio">
    <span>Bio</span>
    <p>
      <%= @user.bio %>
    </p>
  </div>
  <% @user.recent.each do |post| %>
    <div class="user-posts">
      <p><%=post.title %></p>
      <p><%=post.text %></p>
      <div class="counters">
        <p><strong>Likes:</strong> <%=post.likes_counter%></p>
        <p><strong>Comments:</strong> <%=post.comments_counter%></p>
      </div>
    </div>
    <% end %>
    <%= link_to "<button>See All Posts</button>".html_safe, user_posts_url(@user), :class => 'btn_posts' %>
</div>
  